#!/usr/bin/env node
'use strict';

var stdio = require('stdio'),
    fs = require('fs'),
    clc = require('cli-color');

var args = process.argv.slice(2);


var cli = {
  args: args,
  getopt: stdio.getopt,
  prefix: '[' + clc.cyan('form5') + ']',
  log: function(message){ console.log( cli.prefix, message ); },
  notice: function(message){ console.log( cli.prefix, clc.blue(message) ); },
  success: function(message){ console.log( cli.prefix, clc.green(message) ); },
  warn: function(message){ console.log( cli.prefix, clc.yellow(message) ); },
  error: function(message){ console.log( cli.prefix, clc.red.bold(message) ); }
};


// Prints CLI general help and lists available commands
var printHelp = function() {
  console.log('Usage: form5 COMMAND [options]');
  console.log('For command specific help type form5 command -h or --help \n');
  console.log('Available commands:');

  fs.readdir(__dirname + '/tasks/', function(err, files) {
    for (var i = 0; i < files.length; i++) {
      console.log(files[i].split('.')[0]);
    };
  });
};


// Parse arguments and run the appropriate command
if(args.length) {
  if(fs.existsSync(__dirname + '/tasks/' + args[0] + '.js')) {
    require(__dirname + '/tasks/' + args[0] + '.js')(cli);
  } else {
    console.log('Unkown option: ' + args[0]);
    printHelp();
  }
} else {
  printHelp();
}
