#!/usr/bin/env node
'use strict';

var stdio = require('stdio'),
    fs = require('fs'),
    clc = require('cli-color');

var args = process.argv.slice(2);

var cli = {
  getopt: stdio.getopt,
  notice: function(message) { console.log(clc.blueBright(message)); },
  warn: function(message) { console.log(clc.yellow(message)); },
  error: function(message) { console.log(clc.red.bold(message)); }
};


// Prints CLI general help and lists available commands
var printHelp = function() {
  console.log('Usage: form5 COMMAND [options]');
  console.log('For command specific help type form5 command -h or --help \n');
  console.log('Available commands:');

  fs.readdir('./tasks/', function(undefined, files) {
    for (var i = 0; i < files.length; i++) {
      console.log(files[i].split('.')[0]);
    };
  });
};


// Parse arguments and run the appropriate command
if(args.length) {
  if(fs.existsSync('./tasks/' + args[0] + '.js')) {
    require('./tasks/' + args[0] + '.js')(cli);
  } else {
    console.log('Unkown option: ' + args[0]);
    printHelp();
  }
} else {
  printHelp();
}
